service: sample-secure

plugins:
  - serverless-plugin-typescript
  - serverless-webpack
  - serverless-offline
  - serverless-aws-documentation

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 6 # optional, in seconds, default is 6

  stage: ${env:SLS_AWS_STAGE}
  region: ${env:SLS_AWS_REGION}

package:
  individually: true
  exclude:
    - ".*/**"

functions:
  sample-secure:
    handler: src/index.handler

    package:
      include:
        - src/**

    events:
      - http:
          path: sample-secure
          method: get
          authorizer:
            type: request
            arn: ${env:SLS_AUTHORIZER_ARN}

custom:
  dotenv:
    path: .env

  webpack:
    webpackConfig: '../../../webpack.config.js'
