service: sample-authorizer

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 6 # optional, in seconds, default is 6

  stage: ${env:SLS_AWS_STAGE}
  region: ${env:SLS_AWS_REGION}

  environment:
      SLS_AUTHORIZER_SHARED_SECRET: ${env:SLS_AUTHORIZER_SHARED_SECRET}

package:
  individually: true
  exclude:
    - ".*/**"

functions:
  sample-authorizer:
    handler: build/index.handler

    package:
      include:
        - build/**

    events:
      - http:
          path: sample-authorizer
          method: get

custom:

  webpack:
    webpackConfig: '../../webpack.config.js'
