service: sample-kms

plugins:
  - serverless-kms-secrets
  - serverless-plugin-typescript
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-aws-documentation

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 6 # optional, in seconds, default is 6

  stage: ${env:SLS_AWS_STAGE}
  region: ${env:SLS_AWS_REGION}

  environment: ${file(./serverless-aws-environment.yml):environment}

  stackTags: ${file(./serverless-aws-tags.yml):stackTags}

  role: ${env:SLS_AWS_EXECUTION_ROLE}

package:
  individually: true
  exclude:
    - ".*/**"

functions: ${file(./serverless-aws-functions.yml):functions}

resources: ${file(./serverless-aws-resources.yml):resources}

custom:
  webpack:
    webpackConfig: '../../../webpack.config.js'

  kmsSecrets: ${file(kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}

  dynamodb:
    start:
      seed: true

    seed:
      testdata:
        sources:
          - table: samplekmsdb
            sources: [./samplekmsdb.seed.json]

