environment:
  HERITAGE: generator-mono-serverless:package
  SLS_AWS_STAGE: ${env:SLS_AWS_STAGE, 'dev'}
  SLS_AWS_REGION: ${env:SLS_AWS_REGION, 'ap-southeast-2'}
  SLS_APIGW_ENDPOINT_TYPE: ${env:SLS_APIGW_ENDPOINT_TYPE, 'EDGE'}
  SLS_SNS_ERROR_TOPIC_ARN: ${env:SLS_SNS_ERROR_TOPIC_ARN}
  SLS_DEPLOYMENT_S3_BUCKET_PREFIX: ${env:SLS_DEPLOYMENT_S3_BUCKET_PREFIX}
  SLS_AWS_KMS_KEY_ID: ${env:SLS_AWS_KMS_KEY_ID}
  SLS_AWS_EXECUTION_ROLE: ${env:SLS_AWS_EXECUTION_ROLE}
  SLS_DYNAMODB_TABLENAME: ${env:SLS_DYNAMODB_TABLENAME}
