service: sample-default

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 2048 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6

  stage: "dev" # ${env:SLS_AWS_STAGE}
  region: "ap-southeast-2" # ${env:SLS_AWS_REGION}

  environment:
      PLACE: "holder"

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:UpdateItem
      Resource:
        Fn::GetAtt: [ slsSampleDefault, Arn ]

package:
  individually: true
  exclude:
    - ".*/**"

functions:
  sample-default:
    handler: build/index.handler
    environment:
      slsSampleDefault:
        Ref: slsSampleDefault

    package:
      include:
        - build/**

    events:
      - http:
          path: sample-default
          method: get

resources:
  Resources:
    slsSampleDefault:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: slsSampleDefault
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_IMAGE

custom:
  dotenv:
    path: .env

  webpack:
    webpackConfig: '../../webpack.config.js'
