service: sample-default

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-offline-localstack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 6 # optional, in seconds, default is 6

  stage: ${env:SLS_AWS_STAGE}
  region: ${env:SLS_AWS_REGION}

  environment:
      PLACE: "holder"

package:
  individually: true
  exclude:
    - ".*/**"

functions:
  echo:
    handler: build/index.handler

    package:
      include:
        - build/**

    events:
      - http:
          path: echo
          method: get

custom:
  webpack:
    webpackConfig: '../../webpack.config.js'

  serverlessOfflineLocalstack:
    stages:
      - local
    endpointFile: serverlessOfflineLocalstack.json

  domains:
    prod: ${env:SLS_CUSTOM_DOMAIN}
    sit: sit.${env:SLS_CUSTOM_DOMAIN}
    dev: dev.${env:SLS_CUSTOM_DOMAIN}
    local: ''

  dnsEnabled:
    prod: true
    sit: true
    dev: true
    local: false

  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    certificateName: ${env:SLS_CUSTOM_DOMAIN}
    basePath: ${self:service}
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: regional
    enabled: ${self:custom.dnsEnabled.${self:provider.stage}}
